### ISSUE TITLE
Can't connect to CRM D365 V9 with 2FA enable

### ISSUE THREAD

**Issue by marksalendu** [yagasoft/DynamicsCrm-CodeGenerator#2]
Can't connect to CRM D365 Online (v9) with 2FA enabled.

![image](https://user-images.githubusercontent.com/8477424/84587418-4c0d3100-ae49-11ea-865a-e2286aa59d55.png)

![image](https://user-images.githubusercontent.com/8477424/84587426-5e876a80-ae49-11ea-940b-f9702230f749.png)

**Comment by yagasoft** [comment]
I will perform a revamp of the login to accommodate the new features of the connection through SDK.

**Comment by yagasoft** [comment]
Tool updated to use explicit Connection Strings and upgraded to the latest SDK version.

**Comment by koehler0179** [comment]
Why not connecting to O365 via ClientId and ClientSecret? Works like a charm. Codegeneration should not happen with a normal user anyway in my opinion.
