### ISSUE TITLE
ConnectionString Error

### ISSUE THREAD

**Issue by bkorbuly** [yagasoft/DynamicsCrm-CodeGenerator#3]
Hi,

I am trying to connect to the CRM as shown on the [webpage](http://blog.yagasoft.com/2020/09/dynamics-template-based-code-generator-supercharged). 
The problem is the ClientSecret ends with the equation character('='). Therefore the tool is replacing my equation character to this string: " = ". 
So when the tool tries to establish a connection the response is "invalid client secret provided".

Can you help me with this issue or am I missing something out?
Thanks in advance

**Comment by yagasoft** [comment]
As a workaround, please regenerate a Client Key on Azure. I will work on a resolution for this issue soon.
Thank you for your feedback.

**Comment by yagasoft** [comment]
Resolved in v10.5.1.
