### ISSUE TITLE
VS 2015 crash after install vs package extension

### ISSUE THREAD

**Issue by marksalendu** [yagasoft/DynamicsCrm-CodeGenerator#5]
I have installed previous version of this extension into vs 2015, and deployed into my crm projects.
But after update to latest version, every time I open vs 2015 it always crashed.

I try to download the code from this repository, and can't open it properly. It seems not compatible with VS 2015 because of C# 7.1 not installed. 

Is it possible because of this compatibility issue, vs 2015 crash every time I open it?

**Comment by yagasoft** [comment]
Hello,
Please excuse the delay in response; I did not get a notification for some reason.
Try to uninstall and reinstall it again. I will install VS 2015 and try from my end if that doesn't work for you.

**Comment by yagasoft** [comment]
Upon debugging, this is the error being thrown:
> System.TypeLoadException: 'Could not load type 'Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCacheNotification' from assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.19.8.16603, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.'

Going all the way back to September, there was no change in the C# version or packages since then, other than the EnhancedOrgService one.

If you can remember the version that worked, I can rollback to it, compile it, and send it to you.

**Comment by yagasoft** [comment]
Limiting extension to VS v15+ (2017+). Will take effect starting from the next version.
