### ISSUE TITLE
Setting not saved correctly in VS plugin

### ISSUE THREAD

**Issue by koehler0179** [yagasoft/DynamicsCrm-CodeGenerator#7]
In the Dialog of the VS plugin there is an option called "Use CRM labels for variable names". Looks like this setting is not saved after closing the dialog and saving the options. If you re-generate the code and open the dialog again you always have to uncheck that option first again before generation to get the same code out.
![image](https://user-images.githubusercontent.com/66683035/119633446-0b1beb80-be12-11eb-8ae3-44426cfb75dd.png)

**Comment by yagasoft** [comment]
@koehler0179 
Please excuse my delayed response. For some reason, GitHub is not sending me notifications about issues.
Thank you for reporting the issue. It has been resolved in the new version.

**Comment by koehler0179** [comment]
What delay? Faster than amazon 😁. THX!
